# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: 2025-2026 Tenstorrent USA, Inc.

"""Model catalog: the bundled model_support.json + HF cache scan.

model_support.json is generated by scripts/build_model_support.py from
tt-inference-server's release_model_spec.json at the tag pinned in
tools/supplement.toml, with model_support_overrides.toml applied on top — the
boards a model is known to fail on, the meshes it can borrow a spec from, and
the flags `tt serve` has to pass because the spec's own value is wrong. Reading
the generated file rather than the spec keeps one parser (the build script's)
and lets the same artifact ship, publish, and drive the CLI.
`TT_MODEL_SUPPORT_PATH` overrides the bundled file.

ModelCatalog is the only consumer-facing surface. It merges an ordered list of
entry sources, later sources overriding earlier ones by ModelInfo.name; today
that list is just ModelSupportSource. tt-model bundles (tt-model-manager's
self-contained running folders, `tt_kernel_manifest.json` on disk) are
deliberately NOT a source here: they share no schema with the compat spec (no
per-device status, no max_context), so `modelhub/bundles.py` lists them
separately for `tt model list --community`.
Cache state comes from `huggingface_hub.scan_cache_dir`, so `tt model list`
shows what is actually on disk regardless of which tool downloaded it.
"""

from __future__ import annotations

import dataclasses
import json
import os
from importlib import resources
from pathlib import Path
from typing import Protocol, Sequence

from ..errors import ExitCode, TTError
from ..models.model import DeviceSupport, ModelInfo, Unsupported

SUPPORT_SCHEMA_VERSION = 1
SUPPORT_PATH_ENV = "TT_MODEL_SUPPORT_PATH"


def _load_support_text() -> tuple[str, str]:
    override = os.environ.get(SUPPORT_PATH_ENV)
    if override:
        path = Path(override)
        if not path.exists():
            raise TTError(
                f"{SUPPORT_PATH_ENV} points at {path}, which does not exist.",
                next_step=f"Fix or unset {SUPPORT_PATH_ENV} to use the bundled list.",
                exit_code=ExitCode.CONFIG,
            )
        return path.read_text(), str(path)
    return (
        (resources.files("tenstorrent.modelhub") / "model_support.json").read_text(),
        "bundled model_support.json",
    )


def _config_error(origin: str, what: str, why: str | None = None) -> TTError:
    return TTError(
        f"Model support list at {origin} {what}",
        why=why,
        next_step=f"Reinstall tt, or fix {SUPPORT_PATH_ENV}.",
        exit_code=ExitCode.CONFIG,
    )


def _device_support(device: str, raw: dict, origin: str) -> DeviceSupport:
    supported = bool(raw.get("supported", True))
    mark = raw.get("unsupported") if isinstance(raw.get("unsupported"), dict) else None
    if not supported:
        # `tt serve` refuses on a mark and quotes it, so an empty one would refuse
        # with no explanation and no date to judge it by.
        missing = [f for f in ("reason", "details", "verified_on") if not (mark or {}).get(f)]
        if missing:
            raise _config_error(
                origin,
                f"marks {device} unsupported without {', '.join(missing)}.",
            )
    return DeviceSupport(
        engines=list(raw.get("engines") or []),
        status=str(raw.get("status", "")),
        max_context=raw.get("max_context"),
        supported=supported,
        unsupported=Unsupported(
            reason=str(mark.get("reason", "")),
            details=str(mark.get("details", "")),
            verified_on=str(mark.get("verified_on", "")),
            source=str(mark.get("source", "")),
        )
        if mark and not supported
        else None,
        docker_image=raw.get("docker_image"),
        impl_id=raw.get("impl_id"),
        version=raw.get("version"),
        tool_call_parser=raw.get("tool_call_parser"),
        reasoning_parser=raw.get("reasoning_parser"),
        override_tt_config=raw.get("override_tt_config"),
        serve_overrides=raw.get("serve_overrides"),
        serve_as=raw.get("serve_as"),
        support_source=str(raw.get("support_source", "spec")),
        note=str(raw.get("note", "")),
    )


def parse_model_support(text: str, origin: str) -> tuple[str, list[ModelInfo]]:
    """Parse model_support.json into (release_version, entries).

    The file is generated by scripts/build_model_support.py from the pinned
    release spec plus model_support_overrides.toml, so this is a plain read: all
    the spec flattening, the marks and the mesh substitutions already happened at
    build time, and CI regenerates the file to keep it in step with its inputs.
    """
    try:
        doc = json.loads(text)
    except json.JSONDecodeError as exc:
        raise _config_error(origin, "is not valid JSON.", why=str(exc)) from exc
    if not isinstance(doc, dict) or doc.get("schema_version") != SUPPORT_SCHEMA_VERSION:
        raise _config_error(origin, "has unsupported schema_version.")

    entries = []
    for raw in doc.get("models") or []:
        devices = {
            device: _device_support(device, detail, origin)
            for device, detail in (raw.get("devices") or {}).items()
        }
        if not devices:
            continue
        entries.append(
            ModelInfo(
                name=str(raw["name"]),
                hf_repo=str(raw.get("hf_repo", "")),
                # `tt model list --type` compares against a lowercased filter, so
                # the invariant has to hold for a hand-written list too.
                model_type=str(raw.get("model_type", "")).lower(),
                engines=list(raw.get("engines") or []),
                tt_model_id=raw.get("tt_model_id"),
                hardware=list(devices),
                devices=devices,
                param_count=raw.get("param_count"),
                min_disk_gb=raw.get("min_disk_gb"),
                min_ram_gb=raw.get("min_ram_gb"),
            )
        )
    return str(doc.get("release_version", "")), entries


class ModelSupportSource:
    """The bundled, generated support list (or TT_MODEL_SUPPORT_PATH)."""

    def __init__(self) -> None:
        text, self.origin = _load_support_text()
        self.release_version, self._entries = parse_model_support(text, self.origin)

    def entries(self) -> list[ModelInfo]:
        return self._entries


class CatalogSource(Protocol):
    origin: str

    def entries(self) -> list[ModelInfo]: ...


def scan_hf_cache() -> dict[str, int]:
    """repo_id → size on disk, for models present in the HuggingFace cache."""
    from huggingface_hub import scan_cache_dir
    from huggingface_hub.errors import CacheNotFound

    try:
        info = scan_cache_dir()
    except CacheNotFound:
        return {}
    return {
        repo.repo_id: repo.size_on_disk
        for repo in info.repos
        if repo.repo_type == "model"
    }


def unknown_model_error(name: str, origin: str) -> TTError:
    return TTError(
        f"Unknown model {name!r}.",
        why=f"It is not in the model catalog ({origin}).",
        next_step="Run `tt model list` to browse available models.",
        exit_code=ExitCode.USAGE,
    )


class ModelCatalog:
    def __init__(self, sources: Sequence[CatalogSource] | None = None) -> None:
        # Ordered entry sources, merged by ModelInfo.name with later sources
        # winning, so an appended source can override the released spec's entry
        # of the same name. tt-model bundles are kept out of this list on
        # purpose — see modelhub/bundles.py.
        self.sources: list[CatalogSource] = (
            list(sources) if sources is not None else [ModelSupportSource()]
        )
        self.origin = " + ".join(s.origin for s in self.sources)

    def list(self, *, cached_sizes: dict[str, int] | None = None) -> list[ModelInfo]:
        cached_sizes = cached_sizes if cached_sizes is not None else scan_hf_cache()
        merged: dict[str, ModelInfo] = {}
        for source in self.sources:
            for entry in source.entries():
                merged[entry.name] = entry
        return [
            dataclasses.replace(
                entry,
                cached=entry.hf_repo in cached_sizes,
                cache_size_bytes=cached_sizes.get(entry.hf_repo),
            )
            for entry in sorted(merged.values(), key=lambda e: e.name.lower())
        ]

    def find(
        self, name: str, *, cached_sizes: dict[str, int] | None = None
    ) -> ModelInfo | None:
        """The entry matching `name` (model_name or hf_repo, case-insensitive), or
        None. `tt serve` uses this to decide whether a name belongs to
        tt-inference-server before falling back to another serving path."""
        wanted = name.lower()
        for model in self.list(cached_sizes=cached_sizes):
            if wanted in (model.name.lower(), model.hf_repo.lower()):
                return model
        return None

    def get(self, name: str, *, cached_sizes: dict[str, int] | None = None) -> ModelInfo:
        model = self.find(name, cached_sizes=cached_sizes)
        if model is None:
            raise unknown_model_error(name, self.origin)
        return model
